# ----------------------------------
# Initial .travis.yml file
# ----------------------------------
.branches:
  # all branches

language: python

python:
#  - "3.6"      # current default Python on Travis CI
  - "3.7"
#  - "3.8"
#  - "3.8-dev"  # 3.8 development branch
# command to install dependencies

install:
  - cd server
  - pip install -r requirements/dev.txt
  - cd ../

# command to run tests
script:
  - cd server
  # Note: For now excluding tests that use the Django web client, e.g. uses the requests lib
  - python manage.py test opendp_apps.dataverses.testing.test_dataverse_incoming.DataverseIncomingTest.test_010_dv_params opendp_apps.dataverses.testing.test_dataverse_incoming.DataverseIncomingTest.test_020_check_dv_handler_directly
  - cd ../
